version: "3"

services: 
    angular-app:
      build: 
        context: .
        dockerfile: ./frontend/Dockerfile
      stdin_open: true
      ports: 
        - 4200:4200
      volumes:
        - ./frontend/src:/app/frontend/src
      command: npm run start
      restart: always
